# Generated by Django 3.1.13 on 2025-07-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
