# Generated by Django 3.1.13 on 2025-07-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0002_auto_20250720_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhaar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='purpose',
            field=models.CharField(max_length=30),
        ),
    ]
